#ifndef __USER_CONFIG_H__
#define __USER_CONFIG_H__

#define USE_WIFI_MODE		STATIONAP_MODE
#define WIFI_CLIENTSSID		"YOURSSID"
#define WIFI_CLIENTPASSWORD	"PASSWORD"
#define WIFI_AP_NAME		"ESP8266"
#define WIFI_AP_PASSWORD	"000000"
#define TCPSERVERIP		"172.20.7.62"
#define TCPSERVERPORT		6969
#define PLATFORM_DEBUG		true
#define DEVICE_ID	"abcdefgh"
//#define LWIP_DEBUG		true

#endif
